export const chainNameMap = {"AME":"AME",
"ARBITRUM":"ARB",
"AVALANCHE":"AVAXC",
"BASE":"BASE",
"BRC20":null,
"BRISE":"BRISE",
"BSC":"BSC",
"BTC": null,
"BTTC":"BTTC",
"CELO":"CELO",
"CFX":"CFX",
"CORE":"CORE",
"CRONOS":"CRONOS",
"CRU": null,
"CUBE":"CUBE",
"DBC": null,
"DOT": null,
"DRAC":"DRAC",
"EOS": null,
"ETC":"ETC",
"ETH":"ETH",
"ETHF":"ETHF",
"ETHW":"ETHW",
"EVM":"EVM",
"FANTOM": null,
"FIL": null,
"FVM":"FVM",
"GNOSIS":"GNOSIS",
"GRC30":"GRC",
"HECO":"HECO",
"HPB":"HPB",
"KAVA": null,
"KCC":"KCC",
"KLAYTN":"KLAY",
"LINEA":"LINEA",
"MTR":"MTR",
"OKEXCHAIN":"OKExChain",
"OPTIMISM":"Optimism",
"ORC":"ORC",
"PEGO":"PEGO",
"POLYGON":"POLYGON",
"PULSECHAIN":"PulseChain",
"SCROLL":"SCROLL",
"SEI": null,
"SOLANA":"SOL",
"SUI": null,
"TRON":"TRX",
"TT":"TT",
"XDC":"XDC",
"XRP": null,
"ZKSYNC":"ZKSYNC",
"opBNB":"OPBNB"
}
